version: 2
updates:
  - package-ecosystem: composer
    open-pull-requests-limit: 20
    versioning-strategy: widen
    directory: "/"
    schedule:
      interval: weekly
      day: friday
  - package-ecosystem: npm
    open-pull-requests-limit: 20
    versioning-strategy: widen
    directory: "/website"
    schedule:
      interval: weekly
      day: friday
    groups:
      docusaurus:
        patterns:
          - "@docusaurus/*"
      react:
        patterns:
          - react
          - react-*
          - "@types/react"
          - "@types/react-*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: friday
    groups:
      laminas:
        patterns:
          - "laminas/*"
      phpstan:
        patterns:
          - "phpstan/*"
          - "slam/phpstan-laminas-framework"
      phpunit:
        patterns:
          - "phpunit/*"
          - "spatie/phpunit-snapshot-assertions"
