name: Publish

on:
  push:
    tags: [v*]

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - uses: actions/setup-node@v2.5.1
        id: setup-node
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          cache: yarn
          cache-dependency-path: website/yarn.lock

      - name: ⚙️ Install Dependencies
        if: steps.setup-node.outputs.cache-hit != 'true'
        working-directory: website
        run: yarn

      - name: 🔑 Add key to allow access to repository
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: 🚀 Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
        working-directory: website
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

          npx docusaurus deploy
