name: Publish

on:
  push:
    tags: [v*]

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          cache: yarn

      - name: ⚙️ Install Dependencies
        run: yarn

      - name: 🔑 Add key to allow access to repository
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.GH_PAGES_DEPLOY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat <<EOT >> ~/.ssh/config
          Host github.com
          HostName github.com
          IdentityFile ~/.ssh/id_rsa
          EOT

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: 🚀 Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          cd website
          yarn install --frozen-lockfile
          npx docusaurus docs:version ${{ steps.get_version.outputs.version }}
          echo `git add -A && git commit -m "docs: release new version"`
          git push --follow-tags origin master
          npx docusaurus deploy
