name: Publish

on:
  push:
    tags: [v*]

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/build-website.yml
        with:
          publish: true
